/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage Task1_Icon;
extern const Sifteo::AssetImage TaskReds;
extern const Sifteo::AssetImage Task2_Icon;
extern const Sifteo::AssetImage Task3_Icon;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage TaskYellows;
extern const Sifteo::AssetImage TaskBlues;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage Bars[4];
