/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootAssets;
extern const Sifteo::AssetImage Title;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage Playfield;
extern const Sifteo::AssetImage StripesPlayfield;
extern const Sifteo::AssetImage PlayfieldF;
extern const Sifteo::AssetImage Markers;
extern const Sifteo::AssetImage Brackets;
extern const Sifteo::AssetImage PlayfieldE;
extern const Sifteo::AssetImage PlayfieldA;
extern const Sifteo::AssetImage PlayfieldW;
extern const Sifteo::PinnedAssetImage Particle0;
extern const Sifteo::PinnedAssetImage Particle0Warp;
extern Sifteo::AssetGroup MenuGroup;
extern const Sifteo::AssetImage MenuIconSpinny;
extern const Sifteo::PinnedAssetImage MenuStripe;
extern const Sifteo::PinnedAssetImage MenuBg;
extern const Sifteo::AssetImage MenuFooter;
extern const Sifteo::AssetImage MenuLabelEmpty;
extern const Sifteo::AssetImage MenuIconBall;
extern const Sifteo::AssetImage LoadingBg;
extern Sifteo::AssetGroup SpinnyGroup;
extern const Sifteo::AssetImage Spinny;
extern Sifteo::AssetGroup BallGroup;
extern const Sifteo::AssetImage Ball;
