/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::PinnedAssetImage PurpleTile;
extern const Sifteo::AssetImage task1;
extern const Sifteo::AssetImage task2;
extern const Sifteo::AssetImage task3;
extern const Sifteo::AssetImage task1_complete;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage task2_complete;
extern const Sifteo::AssetImage task3_complete;
extern const Sifteo::AssetImage task1_selected;
extern const Sifteo::AssetImage task2_selected;
extern const Sifteo::AssetImage task3_selected;
extern const Sifteo::AssetImage purple_label;
extern const Sifteo::AssetImage orange_label;
extern const Sifteo::AssetImage green_label;
extern const Sifteo::AssetImage LabelEmpty;
